i = int(input())
for _ in range(i):
    print(" @@@   @@@ ")
    print("@   @ @   @")
    print("@    @    @")
    print("@         @")
    print(" @       @ ")
    print("  @     @  ")
    print("   @   @   ")
    print("    @ @    ")
    print("     @     ")
